# Password for Prometheus monitoring
monitoringPasscode: "ChangeMe1234!"

# SonarQube edition, can be "developer" or "enterprise", can't be set if community.enabled is true
edition: "enterprise"

service:
  # Since there's no LoadBalancer or Ingress yet, use ClusterIP
  type: ClusterIP

persistence:
  enabled: true
  storageClass: gp2

postgresql:
  postgresqlUsername: "sonarUser"
  postgresqlPassword: "sonarPass"
  postgresqlDatabase: "sonarDB"
  persistence:
    storageClass: gp2
